services:
  traefik:
    image: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  inventoryservice:
    image: development/inventoryservice
    pull_policy: never
    labels:
      - "traefik.http.routers.inventory.rule=PathPrefix(`/api/inventory`)"
      - "traefik.http.services.inventory.loadbalancer.server.port=8080"
    build:
      context: InventoryService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  lendingservice:
    image: development/lendingservice
    pull_policy: never
    labels:
      - "traefik.http.routers.books.rule=PathPrefix(`/api/books`)"
      - "traefix.http.routers.books.service=lending-internal"
      - "traefik.http.routers.lending.rule=PathPrefix(`/api/lending`)"
      - "traefix.http.routers.lending.service=lending-internal"
      - "traefik.http.services.lending-internal.loadbalancer.server.port=8080"
    build:
      context: LendingService
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5136:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  rabbitmq:
    image: rabbitmq:4-management
    labels:
      - "traefik.http.routers.rabbitmq.rule=PathPrefix(`/rabbitmq`)"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s